apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 1001
    volumeMounts:
    - name: cache-volume
      mountPath: /var/cache/nginx
  volumes:
  - name: cache-volume
    emptyDir: {}
